### ISSUE TITLE
Import: Allow multiple file selection

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#240]
[Importing multiple PDF in one shot](/jflesch/paperwork/wiki/FAQ#how-to-import-many-pdf-documents-in-one-shot-) is currently not intuitive at all.
Would be handy to be able to select multiple PDF files in one shot.

**Comment by nodiscc** [comment]
> https://github.com/jflesch/paperwork/wiki/FAQ#how-to-import-many-pdf-documents-in-one-shot-

Note that this only works with directories containing PDF documents, and will not process other files in the directory. Trying to import a directory containing only JPG files returns `Ne sait pas comment importer 'ASSURANCE'. Désolé.`

I have a lot of previously scanned documents in JPG format (that's the default out format for `simple-scan`, a very widespread scanning tool for Linux desktops) and OCRing them in Paperwork works fine, but I have to select them one by one. @jflesch Do you think the importer can be fixed so that it also imports JPG files?

Somewhere near https://github.com/jflesch/paperwork/blob/master/src/paperwork/backend/docimport.py#L95?

**Comment by jflesch** [comment]
What you describe is actually issue #94

**Comment by camlafit** [comment]
Hi

Would be nice to allow subdirectory import ?
When we've yet managed old scan, we can have many directories. Allow a recursive directory import should be a great enhancement.

**Comment by jflesch** [comment]
It's already recursive :-)

**Comment by camlafit** [comment]
Hi

I've just tried and not :)
Only pdf on main directory was imported, all others in sub(sub)directories
not.
Maybe I've forgotten something in my try.

**Comment by jflesch** [comment]
Ok, then it's a bug. I've opened a ticket: #546

**Comment by jflesch** [comment]
31309231348396dfe8d167f760a666011b904f17
