### ISSUE TITLE
Never display nothing

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#399]
Right now, when Paperwork starts or when we click "New document", Paperwork display nothing at all in the page area.

Suggestions from mjourdan ( #356 ):

> we should always have a document selected, so that we have something to show, whether it is the last used, or a new empty doc (in which case we would have a nice message saying "this doc is empty, you can add pages blah blah"). While it is confusing, I wouldn't say it's a blocking issue.

**Comment by tYYGH** [comment]
My opinion: I don’t agree. I find nothing either unnatural or confusing about seeing an empty document. In the real world, there are empty folders; there are empty pages; there are empty notebooks… However, it is a really good idea to have a message like “This is a new, empty, document. You can import or scan new pages inside.”

As for always having a document selected, I even more disagree. When I start Paperwork, it is:
— either because I will scan/imports new documents, in which case being on a new, empty, document is just perfect;
— or because I have a search to do, and then I don’t care at all what document was selected last time.

**Comment by tiramiseb** [comment]
tYYGH, you got a point. An empty doc when starting Paperwork would make sense.
But I don't feel the need for the "New document" entry on the left: an empty document when starting Paperwork could just mean no document is selected.

Maybe instead of an empty document there could be useful information (I don't know which ones), or statistics (number of docs, etc).

**Comment by tYYGH** [comment]
Hum. This is a tough usability/ergonomic issue. While I'd tend to agree with you at first, this would lead to an incoherency between an empty document at the start, and no empty documents after that.

As things are now, bug #403 notwithstanding, I can fire up Paperwork and hit the Scan button right away. Changing that would be a shame. But this implies:
— either an "empty document" concept,
— or a "Scan into new document" button.

**Comment by tiramiseb** [comment]
Which brings us back to my comment there: https://github.com/jflesch/paperwork/issues/356#issuecomment-146576388 
> * "scan or import a new document" on the left panel
> * "scan or import into the current document" on the right panel

**Comment by tYYGH** [comment]
Indeed. Yet I agree that 2 "Scan" buttons is not a good idea. Maybe the solution is to shift the focus from the _action_ to the wanted _result_. For example:
— on the left, there would be a button+drop-down
```
[New Document (from scanner lid)] [↓]
            | (from scanner feeder) |
            | (from file)           |
```
— on the right, for non-PDF documents, there would be a button+drop-down
```
[New Page (from scanner lid)] [↓]
        | (from scanner feeder) |
        | (from file)           |
```

**Comment by jflesch** [comment]
I think those changes could wait for 0.3.1 ? Again, 0.3.0 has to be good, not perfect ;)
Also the discussions here start to become a little bit messy. I'm going to open 0.3.1 milestones and start moving tickets to it. Feel free to open a new ticket for 0.3.1 regarding the "New document" / "Scan to new document" thing

**Comment by tiramiseb** [comment]
tYYGH: your suggestion looks great.
jflesch: agreed.

**Comment by tYYGH** [comment]
Agreed. All things considered, this a minor issue. 0.3.0 is perfectly usable without solving #399.

**Comment by jflesch** [comment]
(Woops, my bad, I didn't realize we already are on a separate ticket. I though I was still reading #356 ... nevermind, please keep going here ... :) )

**Comment by jflesch** [comment]
Here is what I have in mind currently:

When we are on a "New document" (ie when start Paperwork), it will display Paperwork's logo (the paperplane) in big where the pages should be. This is just for aesthetic.

I'm also considering display "notes" : Small text like "Click here to scan or import files" with an arrow pointing to the "scan" button. Not sure if that would really be useful.

I don't know if it's pertinent to do anything more than that.

**Comment by jflesch** [comment]
Actually, I think I'll keep it simple:

When started, it just display the Paperwork + the version.
I guess displaying the version immediately can be handy when it comes to support / bug report.

0c96a4348208e051eb96356022fd16fdc891d859
e6b7137fc999b30ee07dbe38fb2f1848abf0925f

(Note that "Paperwork 1.0" will simply display "Paperwork" ; For some reason, "Paperwork 1.0" looks ugly to me. It makes me think of WIndows 3.11)

**Comment by jflesch** [comment]
![paperwork_welcome](https://cloud.githubusercontent.com/assets/135331/18763189/7fe887ae-810c-11e6-88b9-9335c1c87965.png)

**Comment by jflesch** [comment]
I'm closing this issue for now. Please comment if you see something wrong with this change, and I'll reopen this ticket.
