### ISSUE TITLE
Can't scan from lid

### ISSUE THREAD

**Issue by mjourdan** [jflesch/paperwork#402]
My scanner only has a lid. Sometimes, Paperwork shows me "scan one page" greyed out. I could successfully used it before. However, "scan from feeder" is always available, but I have no feeder.

![capture d ecran de 2015-10-08 19-36-35](https://cloud.githubusercontent.com/assets/5346620/10374723/f368cd64-6df4-11e5-977c-2b9f5c29e8b6.png)

**Comment by tiramiseb** [comment]
I had this once this morning too. Did not find a way to reproduce.

**Comment by jflesch** [comment]
Hm, note that it happens when you are on a PDF:
- "scan single page" always append a page to the current document. But it can't on a PDF
- "scan from feeder" is always enabled if you have a feeder : the multi-scan dialog will then only allow you to create new documents, not append images to the current one.

Also, currently, the "Scan from feeder" option is not yet disabled when you don't have a feeder available. That's something I forgot to in the new UI.

**Comment by jflesch** [comment]
2d70d096c47a40aa1fb1da4da182f5d52a9fd167
3578a7db1379defa49dfe0fc913bdf0c4137a263

Please reopen if you still have problems.
