### ISSUE TITLE
Create a web-frontend or an Owncloud-application as frontend

### ISSUE THREAD

**Issue by torwag** [jflesch/paperwork#427]
Hey, 
similar to #423, I'm looking into a way how to give several users access to a "scanner station" and how to share scanned documents. Since paperwork already splits into a backend and frontend, I was wondering if it would be possible to create a webfrontend instead of the GUI. That would allow to run paperwork on a server (even on a Raspberry Pi) connected to the scanner. People could access the documents from all devices connected to the same network and even start new scanning jobs. 

To avoid developing an entire cloud-space eco-system just for paperwork, it might be an idea to build on top of owncloud. A frontend in form of an owncloud-app could allow to start new scan-jobs and use owncloud as data backend. Thus, one would get sharing, sorting, folders, version control, etc. without the need to reimplenting those features.

**Comment by jflesch** [comment]
Hello,

I think ticket #328 could interest you.

So, yes, it would be possible. However:
* Paperwork is designed to be as simple to install and use as possible. Web servers and web applications are *not* simple to install (yeah, I know, the dependency nightmare of Paperwork doesn't make it easy either as a Gtk GUI ... but package managers are supposed to take care of that).
* I have no use for a web frontend (I sync my files with SparkleShare, and I can access it everywhere I need them). I don't develop features I don't use. Doing otherwise would be the best way to get regressions all the time.
* With a web application, scanning is not an easy problem. You could use any scanner connected on the server side .. but it wouldn't make a lot of sense. You need to scan on the client side, and afaik, it would require a browser plugin.

So I'm not going to implement a web interface. Feel free to do it yourself if you want. I will gladly help you with any questions about Paperwork backend you might have.

**Comment by tYYGH** [comment]
In case someone is interested, I wrote a CLI+Web front-end:
http://yalis.fr/cms/index.php/post/2016/01/21/Command-line-and-Web-Interface-for-Paperwork
Cheers,
