### ISSUE TITLE
Previews not shown

### ISSUE THREAD

**Issue by smurfix** [jflesch/paperwork#456]
How to reproduce:
- start paperwork
- import a PDF
- no preview is displayed
- add a keyword
- voilà, preview! 

Also, possibly related:

```
INFO   paperwork.frontend.mainwindow.scan Animator: Angle 0: (20, 0) (473, 669) -> (213, 10) (453, 649)
INFO   paperwork.frontend.mainwindow.scan Failed to use OCR tool heuristic for orientation detection: 'NoneType' object has no attribute '__getitem__'
INFO   paperwork.frontend.mainwindow.scan Falling back on Paperwork's heuristic

```

**Comment by jflesch** [comment]
Have you installed Tesseract or Cuneiform ?

**Comment by jflesch** [comment]
Also, would it be possible to have the full output of Paperwork please ?

**Comment by jflesch** [comment]
ping ?

**Comment by smurfix** [comment]
Sorry about the delay. I have since eliminated the problem, probably as a side effect of also eliminating a ton of index reloads, because that causes excessive delay in the workflow when you have 1000+ documents. See my git tree for the heap of changes. That tree unfortunately also has some other changes mixed in which I need, like the ability to split PDFs at multiple points simultaneously (too slow otherwise) and associating a page-sequential number with a tag, which I need for filing the paper originals so that I can find the originals if/when the tax people want them.

My next idea, which I haven't really started working on but need to, is to keep all original documents (and document pages), piece "real" documents together by referring to these pages instead of rewriting PDFs or rearranging JPEGs (thereby being able to digitally sign the originals, required for storing tax files and whatnot; this would also allow me to mix PDF and images in one document), and store all of these relationships in a database (sqlalchemy is your friend).

**Comment by jflesch** [comment]
1) You should work on the branch 'unstable' , not the branch 'stable'. ['stable' is only for bugfixes](https://github.com/jflesch/paperwork/wiki/Branches).
2) I think it would have been best to [discuss the changes with me before doing them](https://github.com/jflesch/paperwork/wiki/Faq#why-did-you-do-x-instead-of-y-) (ok, I admit this one is buried deep in the FAQ). For examples, I see some changes that break other features in the UI. If you want me to integrate those changes, we will have to fix them first.
3) If you want, I can already go through your commits and either cherry-pick the valid ones in the branch 'unstable', or comment on them to tell you what's wrong.

Regarding the branch 'unstable', there are some things to know:
- [the backend has been split from the frontend](https://github.com/jflesch/paperwork-backend)
- It must be used with Python 3
- At the moment, scanning is broken. It segfaults. I think it's due to the changes in src/paperwork/backend/util.py I had to make to switch to Python 3 (image2surface() and surface2image() have been changed).

**Comment by jflesch** [comment]
ping ?
