### ISSUE TITLE
Crashrecovery of index

### ISSUE THREAD

**Issue by jmankiewicz** [jflesch/paperwork#562]
Hi Folks!

After a crash of paperwork, it could not load the documents and ended up eternally loading. Deleting the index-folder solved this problem for me. 

(I had not enough time here at work to figure out if it was caused by a stale lock or misformed index files. Sorry. Maybe someone else can test when the problem occurs to them?)

Suggestion:

Popup a dialog if loading the index takes too long or the index is not readable, from which the user can force reindexing or the deletion of stale lock-files.

Thanks !

Jörn

**Comment by jflesch** [comment]
The output of the [diagnostic dialog](https://openpaper.work/fr/helpdesk/kb/1/) would have been handy :/
Also, I'm not really sure covering cases that shouldn't happen in a first place is a really good long-term strategy.

**Comment by jmankiewicz** [comment]
> The output of the diagnostic dialog would have been handy :/

I had a quick look and it didn't seem conclusive. With my boss literally standing behind me and breathing down my neck I had to find a really fast solution.

> Also, I'm not really sure covering cases that shouldn't happen in a first place is a really good long-term strategy.

I totally agree to that, don't get me wrong. But we can't keep a normal user (TM) waiting forever if something with loading the index goes horribly wrong. We have to somehow recover to a safe state even then. Think of it as last line of defence.

**Comment by jflesch** [comment]
Currently, when Paperwork cannot open the index, it destroys it and remake it from scratch. So there is already a crash recovery mechanism.

I'm not found of of the popup idea. Because some people have a *lot* of documents, and loading time depends on the number of documents. It would mean they would get the popup everytime.

What I need is the stracktrace when the index doesn't load, so I can run the crash recovery in this case and only this case.

**Comment by jflesch** [comment]
I've had issues with Whoosh recently.
It was the opportunity for me to work on this issue.

Main problem was, all the possible exceptions were not caught correctly in the backend.
It's fixed in the branch unstable: https://github.com/jflesch/paperwork-backend/commit/3912c264ac2ed07c3fb6836148b2eafdea8445f6
